# Longhorn CRDs - Ces CRDs seront créées automatiquement par le manager
# mais on peut les forcer pour accélérer le processus

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumes.longhorn.io
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn-new
spec:
  group: longhorn.io
  names:
    kind: Volume
    listKind: VolumeList
    plural: volumes
    singular: volume
  scope: Namespaced
  versions:
  - name: v1beta2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
