apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system-new
  labels:
    name: longhorn-system-new
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn-new
    app.kubernetes.io/version: v1.10.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: longhorn-1.10.1
