apiVersion: longhorn.io/v1beta2
kind: Settings
metadata:
  name: default-disk-config
  namespace: longhorn-system
spec:
  value:
    disks:
      # Sur talos-w1
      "talos-w1": ["/dev/sdb"]
      # Sur talos-w2
      "talos-w2": ["/dev/sdb"]
