apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-manager
  namespace: longhorn-system
  labels:
    app: longhorn-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-manager
  template:
    metadata:
      labels:
        app: longhorn-manager
    spec:
      serviceAccountName: longhorn-service-account
      # Privilèges requis pour Longhorn
      hostNetwork: true
      hostPID: true
      # Tolérations pour permettre l'exécution sur les nœuds de contrôle si nécessaire
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      # Anti-affinité pour éviter plusieurs instances sur le même nœud
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - longhorn-manager
                topologyKey: kubernetes.io/hostname
      # Priorité pour garantir le scheduling
      priorityClassName: system-cluster-critical
      containers:
        - name: longhorn-manager
          image: longhornio/longhorn-manager:v1.9.2
          imagePullPolicy: IfNotPresent
          # Contexte de sécurité privilégié requis pour accéder aux devices
          securityContext:
            privileged: true
          # Commande avec logging approprié
          command:
            - longhorn-manager
            - -d
            - daemon
            - --engine-image
            - longhornio/longhorn-engine:v1.9.2
            - --instance-manager-image
            - longhornio/longhorn-instance-manager:v1.9.2
            - --share-manager-image
            - longhornio/longhorn-share-manager:v1.9.2
            - --backing-image-manager-image
            - longhornio/backing-image-manager:v1.9.2
            - --support-bundle-manager-image
            - longhornio/support-bundle-kit:v0.0.41
            - --manager-image
            - longhornio/longhorn-manager:v1.9.2
          # Port pour l'API et les webhooks
          ports:
            - containerPort: 9500
              name: manager
              protocol: TCP
            - containerPort: 9501
              name: webhook
              protocol: TCP
            - containerPort: 9502
              name: conversion-wh
              protocol: TCP
          # Readiness probe pour s'assurer que le manager est prêt
          readinessProbe:
            httpGet:
              path: /v1/healthz
              port: 9501
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          # Liveness probe pour redémarrer en cas de problème
          livenessProbe:
            httpGet:
              path: /v1/healthz
              port: 9501
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          # Variables d'environnement
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Configuration Longhorn par défaut
            - name: DEFAULT_SETTING_PATH
              value: /var/lib/longhorn-setting/longhorn-default-setting.yaml
            - name: LONGHORN_BACKEND_SVC
              value: longhorn-backend
            - name: LONGHORN_MANAGER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          # Ressources recommandées
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          # Montages de volumes
          volumeMounts:
            # Accès aux devices du système
            - name: dev
              mountPath: /host/dev
            # Accès au système de fichiers proc
            - name: proc
              mountPath: /host/proc
              readOnly: true
            # Accès à la configuration du système
            - name: sys
              mountPath: /host/sys
              readOnly: true
            # Docker socket pour la gestion des conteneurs (si Docker)
            - name: docker-socket
              mountPath: /var/run/docker.sock
            # Containerd socket (si containerd)
            - name: containerd-socket
              mountPath: /run/containerd/containerd.sock
            # Configuration Longhorn
            - name: longhorn
              mountPath: /var/lib/longhorn/
              mountPropagation: Bidirectional
            # Settings par défaut
            - name: longhorn-default-setting
              mountPath: /var/lib/longhorn-setting/
            # Montage pour les volumes CSI
            - name: csi
              mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi
              mountPropagation: Bidirectional
            # Répertoire des pods Kubernetes
            - name: kubernetes
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
      volumes:
        # Devices du système
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        # Système de fichiers proc
        - name: proc
          hostPath:
            path: /proc
            type: Directory
        # Système de fichiers sys
        - name: sys
          hostPath:
            path: /sys
            type: Directory
        # Socket Docker
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        # Socket Containerd
        - name: containerd-socket
          hostPath:
            path: /run/containerd/containerd.sock
            type: Socket
        # Données Longhorn
        - name: longhorn
          hostPath:
            path: /var/lib/longhorn/
            type: DirectoryOrCreate
        # Configuration par défaut
        - name: longhorn-default-setting
          configMap:
            name: longhorn-default-setting
            optional: true
        # Montage CSI
        - name: csi
          hostPath:
            path: /var/lib/kubelet/plugins/kubernetes.io/csi
            type: DirectoryOrCreate
        # Pods Kubernetes
        - name: kubernetes
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
---
# Service pour le Longhorn Manager
apiVersion: v1
kind: Service
metadata:
  name: longhorn-backend
  namespace: longhorn-system
  labels:
    app: longhorn-manager
spec:
  type: ClusterIP
  selector:
    app: longhorn-manager
  ports:
    - name: manager
      port: 9500
      targetPort: manager
      protocol: TCP
    - name: webhook
      port: 9501
      targetPort: webhook
      protocol: TCP
    - name: conversion-webhook
      port: 9502
      targetPort: conversion-wh
      protocol: TCP
---
# ConfigMap pour les settings par défaut (optionnel mais recommandé)
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  longhorn-default-setting.yaml: |
    backup-target: ""
    backup-target-credential-secret: ""
    allow-recurring-job-while-volume-detached: "true"
    create-default-disk-labeled-nodes: "true"
    default-data-path: "/var/lib/longhorn/"
    replica-soft-anti-affinity: "true"
    replica-auto-balance: "disabled"
    storage-over-provisioning-percentage: "200"
    storage-minimal-available-percentage: "25"
    upgrade-checker: "true"
    default-replica-count: "3"
    default-data-locality: "disabled"
    guaranteed-engine-manager-cpu: "12"
    guaranteed-replica-manager-cpu: "12"
    orphan-auto-deletion: "true"
    support-bundle-failed-limit: "1"
---
# PriorityClass pour garantir le scheduling
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: longhorn-critical
value: 1000000000
globalDefault: false
description: "Priorité critique pour les composants Longhorn"
---
# ServiceAccount pour Longhorn Manager
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-service-account
  namespace: longhorn-system
---
# ClusterRole pour les permissions nécessaires
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: longhorn-role
rules:
  - apiGroups: [""]
    resources: ["pods", "events", "persistentvolumes", "persistentvolumeclaims", "persistentvolumeclaims/status", "nodes", "proxy/nodes", "pods/log", "secrets", "services", "endpoints", "configmaps"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["daemonsets", "statefulsets", "deployments"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["*"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "volumeattachments", "volumeattachments/status", "csinodes", "csidrivers"]
    verbs: ["*"]
  - apiGroups: ["longhorn.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
  - apiGroups: ["scheduling.k8s.io"]
    resources: ["priorityclasses"]
    verbs: ["watch", "list"]
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["longhorn-psp"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses", "volumesnapshots", "volumesnapshotcontents", "volumesnapshotcontents/status"]
    verbs: ["*"]
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: longhorn-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: longhorn-role
subjects:
  - kind: ServiceAccount
    name: longhorn-service-account
    namespace: longhorn-system
---
# Role pour l'accès au namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: longhorn-role
  namespace: longhorn-system
rules:
  - apiGroups: [""]
    resources: ["pods", "events", "persistentvolumes", "persistentvolumeclaims", "persistentvolumeclaims/status", "nodes", "proxy/nodes", "secrets", "services", "endpoints", "configmaps"]
    verbs: ["*"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: longhorn-bind
  namespace: longhorn-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: longhorn-role
subjects:
  - kind: ServiceAccount
    name: longhorn-service-account
    namespace: longhorn-system