---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    app: longhorn
---
apiVersion: longhorn.io/v1beta2
kind: Settings
metadata:
  name: default-disk-config
  namespace: longhorn-system
spec:
  value:
    disks:
      # Sur talos-w1
      "talos-w1": ["/dev/sdb"]
      # Sur talos-w2
      "talos-w2": ["/dev/sdb"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-manager
  namespace: longhorn-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-manager
  template:
    metadata:
      labels:
        app: longhorn-manager
    spec:
      serviceAccountName: longhorn-service-account
      containers:
        - name: longhorn-manager
          image: longhornio/longhorn-manager:v1.9.2
          volumeMounts:
            - name: dev
              mountPath: /host/dev
      volumes:
        - name: dev
          hostPath:
            path: /dev
