apiVersion: v1
kind: Service
metadata:
  name: dns-service
  namespace: dns
  annotations:
    metallb.universe.tf/address-pool: lan-pool
spec:
  type: LoadBalancer
  selector:
    app: dns-server
  ports:
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
