apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-driver-deployer
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.10.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: longhorn-1.10.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-driver-deployer
  template:
    metadata:
      labels:
        app: longhorn-driver-deployer
        app.kubernetes.io/name: longhorn
        app.kubernetes.io/instance: longhorn
        app.kubernetes.io/version: v1.10.1
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: longhorn-1.10.1
    spec:
      serviceAccountName: longhorn-service-account
      priorityClassName: longhorn-critical
      securityContext:
        runAsUser: 0
      initContainers:
      - name: wait-longhorn-manager
        image: longhornio/longhorn-manager:v1.10.1
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" http://longhorn-backend:9500/v1) != "200" ]; do echo waiting; sleep 2; done
      containers:
      - name: longhorn-driver-deployer
        image: longhornio/longhorn-manager:v1.10.1
        imagePullPolicy: IfNotPresent
        command:
        - longhorn-manager
        - -d
        - deploy-driver
        - --manager-image
        - longhornio/longhorn-manager:v1.10.1
        - --manager-url
        - http://longhorn-backend:9500/v1
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: CSI_ATTACHER_IMAGE
          value: longhornio/csi-attacher:v4.10.0-20251030
        - name: CSI_PROVISIONER_IMAGE
          value: longhornio/csi-provisioner:v5.3.0-20251030
        - name: CSI_NODE_DRIVER_REGISTRAR_IMAGE
          value: longhornio/csi-node-driver-registrar:v2.15.0-20251030
        - name: CSI_RESIZER_IMAGE
          value: longhornio/csi-resizer:v1.14.0-20251030
        - name: CSI_SNAPSHOTTER_IMAGE
          value: longhornio/csi-snapshotter:v8.4.0-20251030
        - name: CSI_LIVENESS_PROBE_IMAGE
          value: longhornio/livenessprobe:v2.17.0-20251030
        - name: CSI_ATTACHER_REPLICA_COUNT
          value: "2"
        - name: CSI_PROVISIONER_REPLICA_COUNT
          value: "2"
        - name: CSI_RESIZER_REPLICA_COUNT
          value: "2"
        - name: CSI_SNAPSHOTTER_REPLICA_COUNT
          value: "2"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
