apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.10.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: longhorn-1.10.1
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
  mkfsOptions: "-E nodiscard"
reclaimPolicy: Delete
volumeBindingMode: Immediate