apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
type: Opaque
data:
  admin-token: enlqVWRNYTZoUFRNRkU4YXVDbC01YjkrYlZKbW9MdFpCY2k5RS9KRDBndz0=VDbC01YjkrYlZKbW9MdFpCY2k5RS9KRDBndz0=
