apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb
      component: controller
  template:
    metadata:
      labels:
        app: metallb
        component: controller
    spec:
      containers:
      - name: controller
        image: quay.io/metallb/controller:v0.14.5
        args:
        - --port=7472
        - --webhook-port=443
