apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: homeassistant
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homeassistant-tls
  namespace: homeassistant
spec:
  secretName: homeassistant-tls
  dnsNames:
  - ha.ga-nan.ovh
  - homeassistant.local
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
