apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/gabinheylen/k8s-gitops.git
    targetRevision: main
    path: infrastructure/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: apps
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/gabinheylen/k8s-gitops.git
#     targetRevision: main
#     path: infrastructure/argocd
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: argocd
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
# ---
# # Application pour déployer le middleware de restriction IP
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: ip-whitelist-middleware
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/gabinheylen/k8s-gitops.git
#     targetRevision: main
#     path: infrastructure/middleware
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: traefik
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
