apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ip-whitelist-middleware
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gabinheylen/k8s-gitops.git
    targetRevision: main
    path: infrastructure/middleware
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
