apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-new
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/gabinheylen/k8s-gitops.git
    targetRevision: main
    path: infrastructure/longhorn-new
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system-new
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
