apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gabinheylen/k8s-gitops.git'
    targetRevision: main
    path: '.'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
