apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/gabinheylen/k8s-gitops.git
    targetRevision: main
    path: dns
    directory:
      recurse: true
      include: "coredns-*.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: dns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
