apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-manifests
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/gabinheylen/k8s-gitops.git'
    targetRevision: main
    path: 'longhorn/core'
    directory:
      recurse: true
      exclude: "*longhorn.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /status
    - /metadata/annotations
    - /metadata/labels
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: 'https://github.com/gabinheylen/k8s-gitops.git'
    targetRevision: main
    path: 'longhorn/ingress'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
