apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
stringData:
  POSTGRES_DB: mycollection
  POSTGRES_USER: mycollection
  POSTGRES_PASSWORD: super-secure-password
