apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
