apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: d29yZHByZXNzX3Bhc3N3b3JkMTIz  # wordpress_password123 (base64 encoded)
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZDEyMw==  # root_password123 (base64 encoded)
  MYSQL_PASSWORD: d29yZHByZXNzX3Bhc3N3b3JkMTIz  # wordpress_password123 (base64 encoded)
