apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ipAddressPools:
  - lan-pool
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-public
  namespace: metallb-system
spec:
  ipAddressPools:
  - public-pool