apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: homeassistant-headers
  namespace: homeassistant
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: http
    customResponseHeaders:
      X-Frame-Options: SAMEORIGIN
    stsSeconds: 0
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: homeassistant
spec:
  redirectScheme:
    scheme: https
    permanent: true
