apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: homeassistant-headers
  namespace: homeassistant
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "homeassistant.local"
      X-Forwarded-For: "true"
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
      X-Content-Type-Options: "nosniff"
      Strict-Transport-Security: "max-age=31536000; includeSubDomains"