apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-data
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
