apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 10m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: "v1.16.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  targetNamespace: cert-manager
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    global:
      leaderElection:
        namespace: cert-manager
    securityContext:
      fsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001
    webhook:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
    cainjector:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
    startupapicheck:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
