apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    pod-security.kubernetes.io/enforce: restricted
---
# Cert Manager is already installed via direct kubectl apply
# This file just ensures namespace exists for ArgoCD tracking
# The actual cert-manager components are managed outside GitOps
# to avoid HelmChart CRD issues
